/** Isolated native window for creating and immediately selecting a Desktop Profile. */

import { BrowserWindow } from 'electron'
import { fileURLToPath } from 'node:url'
import type { DesktopLocale } from './runtime.ts'

const PROFILE_CREATE_SCHEME = 'dsh-profile-create:'
const MAX_NAME_QUERY_BYTES = 1024
const PROFILE_CREATE_DOCUMENT = fileURLToPath(new URL('./native-ui/profile-create.html', import.meta.url))

interface ProfileCreateCopy {
  readonly title: string
  readonly heading: string
  readonly label: string
  readonly placeholder: string
  readonly start: string
  readonly cancel: string
  readonly empty: string
  readonly failed: string
}

const COPY: Record<DesktopLocale, ProfileCreateCopy> = {
  en: {
    title: 'Add Profile',
    heading: 'Create and start a Profile',
    label: 'Profile name',
    placeholder: 'For example: work',
    start: 'Create and Start',
    cancel: 'Cancel',
    empty: 'Enter a Profile name.',
    failed: 'The Profile could not be created. Check the name and try again.',
  },
  zh: {
    title: '添加配置',
    heading: '创建并启动配置',
    label: '配置名称',
    placeholder: '例如：work',
    start: '创建并启动',
    cancel: '取消',
    empty: '请输入配置名称。',
    failed: '配置创建失败，请检查名称后重试。',
  },
}

export interface ProfileCreateWindowOptions {
  readonly locale: DesktopLocale
  readonly onSubmit: (name: string) => void | Promise<void>
}

export interface ProfileCreateAction {
  readonly action: 'submit' | 'cancel'
  readonly name?: string
}

/** Parse only the actions generated by the local profile-create document. */
export function parseProfileCreateAction(href: string): ProfileCreateAction | undefined {
  let url: URL
  try { url = new URL(href) } catch { return undefined }
  if (url.protocol !== PROFILE_CREATE_SCHEME
    || url.username !== '' || url.password !== '' || url.port !== ''
    || url.pathname !== '' || url.hash !== '') return undefined
  const keys = [...url.searchParams.keys()]
  const action = url.hostname
  if (action === 'cancel') return keys.length === 0 ? { action } : undefined
  if (action !== 'submit' || keys.length !== 1 || keys[0] !== 'name') return undefined
  const name = url.searchParams.get('name')
  if (name === null || Buffer.byteLength(name, 'utf8') > MAX_NAME_QUERY_BYTES) return undefined
  return { action, name }
}

/** Own one isolated profile-create window; repeated opens focus the same instance. */
export class ProfileCreateWindow {
  private window: BrowserWindow | undefined
  private busy = false
  private disposed = false

  constructor(private readonly options: ProfileCreateWindowOptions) {}

  open(): void {
    const existing = this.window
    if (existing !== undefined && !existing.isDestroyed()) {
      existing.show()
      existing.focus()
      return
    }
    this.disposed = false
    this.busy = false
    const copy = COPY[this.options.locale]
    const window = new BrowserWindow({
      title: copy.title,
      width: 480,
      height: 360,
      minWidth: 420,
      minHeight: 330,
      resizable: false,
      show: false,
      autoHideMenuBar: true,
      backgroundColor: '#202124',
      webPreferences: {
        contextIsolation: true,
        nodeIntegration: false,
        nodeIntegrationInSubFrames: false,
        sandbox: true,
        webSecurity: true,
        webviewTag: false,
        spellcheck: false,
      },
    })
    this.window = window
    window.accessibleTitle = copy.title
    window.removeMenu()
    window.webContents.setWindowOpenHandler(() => ({ action: 'deny' }))
    const navigate = (event: Electron.Event, href: string): void => {
      const action = parseProfileCreateAction(href)
      event.preventDefault()
      if (action !== undefined) void this.handleAction(action)
    }
    window.webContents.on('will-navigate', navigate)
    window.webContents.on('will-redirect', navigate)
    window.once('ready-to-show', () => {
      if (!this.disposed && this.window === window && !window.isDestroyed()) window.show()
    })
    window.on('closed', () => {
      // Electron destroys webContents before emitting BrowserWindow's `closed`.
      // Accessing window.webContents here can itself throw during a restart.
      if (this.window === window) this.window = undefined
    })
    void window.loadFile(PROFILE_CREATE_DOCUMENT, { query: { locale: this.options.locale } }).catch(() => {
      if (!this.disposed && this.window === window) window.close()
    })
  }

  close(): void {
    this.disposed = true
    const window = this.window
    this.window = undefined
    if (window !== undefined && !window.isDestroyed()) window.close()
  }

  private async handleAction(action: ProfileCreateAction): Promise<void> {
    if (this.busy || this.disposed) return
    if (action.action === 'cancel') {
      this.close()
      return
    }
    const name = action.name?.trim()
    if (name === undefined || name.length === 0) return
    this.busy = true
    try {
      await this.options.onSubmit(name)
      this.close()
    } catch {
      this.busy = false
      const window = this.window
      if (window === undefined || window.isDestroyed()) return
      const message = JSON.stringify(COPY[this.options.locale].failed)
      await window.webContents.executeJavaScript(
        `window.dispatchEvent(new CustomEvent('dsh-profile-create-error', { detail: ${message} }))`,
        true,
      ).catch(() => {})
    }
  }
}
